platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ParticleBox' do

  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'KeychainAccess'
  pod 'Eureka'

  target 'ParticleBoxTests' do
    pod 'Quick'
    pod 'Nimble'
  end
end
